[package]
name = "pop"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
gl = "0.14.0"
log = "0.4.14"
sdl2 = "0.35.1"

[dev-dependencies]
float_eq = "0.7.0"
